
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: root
    password: Mamaitata1
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true

  application:
  name: transfers-realization-service
  profiles:
    active: production
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: "com.commons"
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:



server:
  port: 9991